// Rate component types for logistics industry
export const RATE_COMPONENTS = [
  // Freight & Transportation
  { value: 'freight_charge', label: 'Freight Charge', category: 'Freight & Transportation' },
  { value: 'trucking_origin', label: 'Trucking (Origin)', category: 'Freight & Transportation' },
  { value: 'trucking_destination', label: 'Trucking (Destination)', category: 'Freight & Transportation' },
  { value: 'trucking_door_to_door', label: 'Trucking Door to Door', category: 'Freight & Transportation' },
  { value: 'sea_freight', label: 'Sea Freight', category: 'Freight & Transportation' },
  { value: 'air_freight', label: 'Air Freight', category: 'Freight & Transportation' },
  { value: 'rail_freight', label: 'Rail Freight', category: 'Freight & Transportation' },
  { value: 'barge_freight', label: 'Barge Freight', category: 'Freight & Transportation' },
  { value: 'interisland_freight', label: 'Interisland Freight', category: 'Freight & Transportation' },
  { value: 'local_delivery', label: 'Local Delivery', category: 'Freight & Transportation' },
  { value: 'pickup_charge', label: 'Pickup Charge', category: 'Freight & Transportation' },
  { value: 'first_mile', label: 'First Mile', category: 'Freight & Transportation' },
  { value: 'last_mile', label: 'Last Mile', category: 'Freight & Transportation' },
  { value: 'cross_docking', label: 'Cross Docking', category: 'Freight & Transportation' },
  { value: 'transshipment', label: 'Transshipment', category: 'Freight & Transportation' },
  { value: 'express_delivery', label: 'Express Delivery', category: 'Freight & Transportation' },
  { value: 'same_day_delivery', label: 'Same Day Delivery', category: 'Freight & Transportation' },

  // Port & Terminal Charges
  { value: 'thc_origin', label: 'THC (Origin)', category: 'Port & Terminal' },
  { value: 'thc_destination', label: 'THC (Destination)', category: 'Port & Terminal' },
  { value: 'terminal_handling', label: 'Terminal Handling', category: 'Port & Terminal' },
  { value: 'wharfage', label: 'Wharfage', category: 'Port & Terminal' },
  { value: 'port_charges', label: 'Port Charges', category: 'Port & Terminal' },
  { value: 'container_seal', label: 'Container Seal', category: 'Port & Terminal' },
  { value: 'doc_fee_origin', label: 'Doc Fee (Origin)', category: 'Port & Terminal' },
  { value: 'doc_fee_destination', label: 'Doc Fee (Destination)', category: 'Port & Terminal' },
  { value: 'isps_fee', label: 'ISPS Fee', category: 'Port & Terminal' },
  { value: 'container_tracking', label: 'Container Tracking', category: 'Port & Terminal' },
  { value: 'equipment_handover', label: 'Equipment Handover (EHC)', category: 'Port & Terminal' },
  { value: 'gate_in_out', label: 'Gate In/Out', category: 'Port & Terminal' },
  { value: 'ams_fee', label: 'AMS Fee', category: 'Port & Terminal' },
  { value: 'ens_fee', label: 'ENS Fee', category: 'Port & Terminal' },
  { value: 'vgm_fee', label: 'VGM Fee', category: 'Port & Terminal' },
  { value: 'chassis_fee', label: 'Chassis Fee', category: 'Port & Terminal' },

  // Customs & Documentation
  { value: 'customs_clearance', label: 'Customs Clearance', category: 'Customs & Documentation' },
  { value: 'customs_clearance_import', label: 'Customs Clearance (Import)', category: 'Customs & Documentation' },
  { value: 'customs_clearance_export', label: 'Customs Clearance (Export)', category: 'Customs & Documentation' },
  { value: 'customs_broker_fee', label: 'Customs Broker Fee (PPJK)', category: 'Customs & Documentation' },
  { value: 'import_duty', label: 'Import Duty (Bea Masuk)', category: 'Customs & Documentation' },
  { value: 'export_duty', label: 'Export Duty (Bea Keluar)', category: 'Customs & Documentation' },
  { value: 'vat_ppn', label: 'VAT/PPN', category: 'Customs & Documentation' },
  { value: 'ppn_import', label: 'PPN Import', category: 'Customs & Documentation' },
  { value: 'pph_import', label: 'PPh Import (PPh 22)', category: 'Customs & Documentation' },
  { value: 'pph_23', label: 'PPh 23', category: 'Customs & Documentation' },
  { value: 'quarantine_fee', label: 'Quarantine Fee (Karantina)', category: 'Customs & Documentation' },
  { value: 'fumigation', label: 'Fumigation', category: 'Customs & Documentation' },
  { value: 'certificate_of_origin', label: 'Certificate of Origin (SKA)', category: 'Customs & Documentation' },
  { value: 'legalization_fee', label: 'Legalization Fee', category: 'Customs & Documentation' },
  { value: 'peb_fee', label: 'PEB Fee', category: 'Customs & Documentation' },
  { value: 'pib_fee', label: 'PIB Fee', category: 'Customs & Documentation' },
  { value: 'ls_lartas', label: 'LS/LARTAS', category: 'Customs & Documentation' },
  { value: 'sni_fee', label: 'SNI Fee', category: 'Customs & Documentation' },
  { value: 'bpom_fee', label: 'BPOM Fee', category: 'Customs & Documentation' },
  { value: 'health_certificate', label: 'Health Certificate', category: 'Customs & Documentation' },
  { value: 'phytosanitary', label: 'Phytosanitary Certificate', category: 'Customs & Documentation' },
  { value: 'halal_certificate', label: 'Halal Certificate', category: 'Customs & Documentation' },
  { value: 'notul_fee', label: 'Notul Fee', category: 'Customs & Documentation' },
  { value: 'pnbp_bea_cukai', label: 'PNBP Bea Cukai', category: 'Customs & Documentation' },

  // Handling & Storage
  { value: 'handling_charge', label: 'Handling Charge', category: 'Handling & Storage' },
  { value: 'loading_unloading', label: 'Loading/Unloading', category: 'Handling & Storage' },
  { value: 'loading_charge', label: 'Loading Charge', category: 'Handling & Storage' },
  { value: 'unloading_charge', label: 'Unloading Charge', category: 'Handling & Storage' },
  { value: 'forklift_charge', label: 'Forklift Charge', category: 'Handling & Storage' },
  { value: 'crane_charge', label: 'Crane Charge', category: 'Handling & Storage' },
  { value: 'reach_stacker', label: 'Reach Stacker', category: 'Handling & Storage' },
  { value: 'warehouse_storage', label: 'Warehouse Storage', category: 'Handling & Storage' },
  { value: 'storage_origin', label: 'Storage (Origin)', category: 'Handling & Storage' },
  { value: 'storage_destination', label: 'Storage (Destination)', category: 'Handling & Storage' },
  { value: 'stuffing_unstuffing', label: 'Stuffing/Unstuffing', category: 'Handling & Storage' },
  { value: 'stuffing', label: 'Stuffing', category: 'Handling & Storage' },
  { value: 'unstuffing', label: 'Unstuffing', category: 'Handling & Storage' },
  { value: 'palletization', label: 'Palletization', category: 'Handling & Storage' },
  { value: 'wrapping_packing', label: 'Wrapping/Packing', category: 'Handling & Storage' },
  { value: 'labeling', label: 'Labeling', category: 'Handling & Storage' },
  { value: 'strapping', label: 'Strapping', category: 'Handling & Storage' },
  { value: 'shrink_wrap', label: 'Shrink Wrap', category: 'Handling & Storage' },
  { value: 'crating', label: 'Crating', category: 'Handling & Storage' },
  { value: 'repackaging', label: 'Repackaging', category: 'Handling & Storage' },
  { value: 'segregation', label: 'Segregation', category: 'Handling & Storage' },
  { value: 'sorting', label: 'Sorting', category: 'Handling & Storage' },
  { value: 'lashing', label: 'Lashing', category: 'Handling & Storage' },
  { value: 'unlashing', label: 'Unlashing', category: 'Handling & Storage' },
  { value: 'dunnage', label: 'Dunnage', category: 'Handling & Storage' },
  { value: 'tally_service', label: 'Tally Service', category: 'Handling & Storage' },
  { value: 'inventory_management', label: 'Inventory Management', category: 'Handling & Storage' },
  { value: 'pick_and_pack', label: 'Pick and Pack', category: 'Handling & Storage' },
  { value: 'kitting', label: 'Kitting', category: 'Handling & Storage' },
  { value: 'return_handling', label: 'Return Handling', category: 'Handling & Storage' },

  // Insurance & Security
  { value: 'cargo_insurance', label: 'Cargo Insurance', category: 'Insurance & Security' },
  { value: 'marine_insurance', label: 'Marine Insurance', category: 'Insurance & Security' },
  { value: 'all_risk_insurance', label: 'All Risk Insurance', category: 'Insurance & Security' },
  { value: 'transit_insurance', label: 'Transit Insurance', category: 'Insurance & Security' },
  { value: 'security_charge', label: 'Security Charge', category: 'Insurance & Security' },
  { value: 'escort_service', label: 'Escort Service', category: 'Insurance & Security' },
  { value: 'security_seal', label: 'Security Seal', category: 'Insurance & Security' },
  { value: 'gps_tracking', label: 'GPS Tracking', category: 'Insurance & Security' },

  // Container & Equipment
  { value: 'container_rental', label: 'Container Rental', category: 'Container & Equipment' },
  { value: 'container_cleaning', label: 'Container Cleaning', category: 'Container & Equipment' },
  { value: 'container_repair', label: 'Container Repair', category: 'Container & Equipment' },
  { value: 'demurrage', label: 'Demurrage', category: 'Container & Equipment' },
  { value: 'detention', label: 'Detention', category: 'Container & Equipment' },
  { value: 'demurrage_detention', label: 'Demurrage & Detention (D&D)', category: 'Container & Equipment' },
  { value: 'reefer_plug_in', label: 'Reefer Plug-in', category: 'Container & Equipment' },
  { value: 'reefer_monitoring', label: 'Reefer Monitoring', category: 'Container & Equipment' },
  { value: 'genset_rental', label: 'Genset Rental', category: 'Container & Equipment' },
  { value: 'pallet_rental', label: 'Pallet Rental', category: 'Container & Equipment' },
  { value: 'crate_rental', label: 'Crate Rental', category: 'Container & Equipment' },
  { value: 'container_deposit', label: 'Container Deposit', category: 'Container & Equipment' },
  { value: 'equipment_return', label: 'Equipment Return', category: 'Container & Equipment' },
  { value: 'flexi_bag', label: 'Flexi Bag', category: 'Container & Equipment' },
  { value: 'iso_tank', label: 'ISO Tank', category: 'Container & Equipment' },
  { value: 'flat_rack', label: 'Flat Rack', category: 'Container & Equipment' },
  { value: 'open_top', label: 'Open Top', category: 'Container & Equipment' },

  // Documentation & Admin
  { value: 'documentation_fee', label: 'Documentation Fee', category: 'Documentation & Admin' },
  { value: 'bill_of_lading_fee', label: 'Bill of Lading Fee', category: 'Documentation & Admin' },
  { value: 'airway_bill_fee', label: 'Airway Bill (AWB) Fee', category: 'Documentation & Admin' },
  { value: 'telex_release', label: 'Telex Release', category: 'Documentation & Admin' },
  { value: 'seaway_bill', label: 'Seaway Bill', category: 'Documentation & Admin' },
  { value: 'manifest_fee', label: 'Manifest Fee', category: 'Documentation & Admin' },
  { value: 'admin_fee', label: 'Admin Fee', category: 'Documentation & Admin' },
  { value: 'communication_fee', label: 'Communication Fee', category: 'Documentation & Admin' },
  { value: 'courier_fee', label: 'Courier Fee', category: 'Documentation & Admin' },
  { value: 'original_doc_fee', label: 'Original Document Fee', category: 'Documentation & Admin' },
  { value: 'amendment_fee', label: 'Amendment Fee', category: 'Documentation & Admin' },
  { value: 'switch_bl', label: 'Switch B/L', category: 'Documentation & Admin' },
  { value: 'letter_of_credit', label: 'Letter of Credit (L/C) Handling', category: 'Documentation & Admin' },
  { value: 'banking_charge', label: 'Banking Charge', category: 'Documentation & Admin' },
  { value: 'translation_fee', label: 'Translation Fee', category: 'Documentation & Admin' },
  { value: 'notary_fee', label: 'Notary Fee', category: 'Documentation & Admin' },

  // Special Services
  { value: 'dangerous_goods_surcharge', label: 'Dangerous Goods Surcharge (DG)', category: 'Special Services' },
  { value: 'hazmat_handling', label: 'Hazmat Handling', category: 'Special Services' },
  { value: 'overweight_surcharge', label: 'Overweight Surcharge', category: 'Special Services' },
  { value: 'oversized_surcharge', label: 'Oversized Surcharge (OOG)', category: 'Special Services' },
  { value: 'overlength_surcharge', label: 'Overlength Surcharge', category: 'Special Services' },
  { value: 'overheight_surcharge', label: 'Overheight Surcharge', category: 'Special Services' },
  { value: 'overwidth_surcharge', label: 'Overwidth Surcharge', category: 'Special Services' },
  { value: 'lift_on_lift_off', label: 'Lift On/Lift Off (LOLO)', category: 'Special Services' },
  { value: 'roll_on_roll_off', label: 'Roll On/Roll Off (RORO)', category: 'Special Services' },
  { value: 'surveyor_fee', label: 'Surveyor Fee', category: 'Special Services' },
  { value: 'sampling_fee', label: 'Sampling Fee', category: 'Special Services' },
  { value: 'inspection_fee', label: 'Inspection Fee', category: 'Special Services' },
  { value: 'pre_shipment_inspection', label: 'Pre-Shipment Inspection', category: 'Special Services' },
  { value: 'temperature_controlled', label: 'Temperature Controlled', category: 'Special Services' },
  { value: 'cold_chain', label: 'Cold Chain', category: 'Special Services' },
  { value: 'pharma_handling', label: 'Pharma Handling', category: 'Special Services' },
  { value: 'special_equipment', label: 'Special Equipment', category: 'Special Services' },
  { value: 'waiting_time', label: 'Waiting Time', category: 'Special Services' },
  { value: 'overnight_charge', label: 'Overnight Charge', category: 'Special Services' },
  { value: 'weekend_surcharge', label: 'Weekend Surcharge', category: 'Special Services' },
  { value: 'holiday_surcharge', label: 'Holiday Surcharge', category: 'Special Services' },
  { value: 'rush_order', label: 'Rush Order', category: 'Special Services' },
  { value: 'project_cargo', label: 'Project Cargo', category: 'Special Services' },
  { value: 'breakbulk', label: 'Breakbulk', category: 'Special Services' },
  { value: 'heavy_lift', label: 'Heavy Lift', category: 'Special Services' },

  // Surcharges
  { value: 'fuel_surcharge', label: 'Fuel Surcharge (BAF/FSC)', category: 'Surcharges' },
  { value: 'bunker_adjustment_factor', label: 'Bunker Adjustment Factor (BAF)', category: 'Surcharges' },
  { value: 'currency_adjustment_factor', label: 'Currency Adjustment Factor (CAF)', category: 'Surcharges' },
  { value: 'peak_season_surcharge', label: 'Peak Season Surcharge (PSS)', category: 'Surcharges' },
  { value: 'congestion_surcharge', label: 'Congestion Surcharge', category: 'Surcharges' },
  { value: 'port_congestion', label: 'Port Congestion Surcharge', category: 'Surcharges' },
  { value: 'low_sulphur_surcharge', label: 'Low Sulphur Surcharge (LSS)', category: 'Surcharges' },
  { value: 'imo_2020', label: 'IMO 2020 Surcharge', category: 'Surcharges' },
  { value: 'war_risk_surcharge', label: 'War Risk Surcharge (WRS)', category: 'Surcharges' },
  { value: 'piracy_surcharge', label: 'Piracy Surcharge', category: 'Surcharges' },
  { value: 'emergency_bunker_surcharge', label: 'Emergency Bunker Surcharge (EBS)', category: 'Surcharges' },
  { value: 'general_rate_increase', label: 'General Rate Increase (GRI)', category: 'Surcharges' },
  { value: 'carrier_security_fee', label: 'Carrier Security Fee', category: 'Surcharges' },
  { value: 'clean_truck_fee', label: 'Clean Truck Fee', category: 'Surcharges' },
  { value: 'remote_area_surcharge', label: 'Remote Area Surcharge', category: 'Surcharges' },
  { value: 'residential_surcharge', label: 'Residential Surcharge', category: 'Surcharges' },
  { value: 'toll_fee', label: 'Toll Fee', category: 'Surcharges' },
  { value: 'highway_fee', label: 'Highway Fee', category: 'Surcharges' },

  // Fulfillment & E-commerce
  { value: 'fulfillment_fee', label: 'Fulfillment Fee', category: 'Fulfillment & E-commerce' },
  { value: 'order_processing', label: 'Order Processing', category: 'Fulfillment & E-commerce' },
  { value: 'value_added_service', label: 'Value Added Service (VAS)', category: 'Fulfillment & E-commerce' },
  { value: 'gift_wrapping', label: 'Gift Wrapping', category: 'Fulfillment & E-commerce' },
  { value: 'insert_packing', label: 'Insert/Packing Slip', category: 'Fulfillment & E-commerce' },
  { value: 'cod_handling', label: 'COD Handling Fee', category: 'Fulfillment & E-commerce' },
  { value: 'cod_remittance', label: 'COD Remittance Fee', category: 'Fulfillment & E-commerce' },
  { value: 'reverse_logistics', label: 'Reverse Logistics', category: 'Fulfillment & E-commerce' },
  { value: 'rts_return_to_sender', label: 'RTS (Return to Sender)', category: 'Fulfillment & E-commerce' },
  { value: 'address_correction', label: 'Address Correction', category: 'Fulfillment & E-commerce' },
  { value: 'redelivery', label: 'Redelivery', category: 'Fulfillment & E-commerce' },
  { value: 'proof_of_delivery', label: 'Proof of Delivery', category: 'Fulfillment & E-commerce' },
  { value: 'signature_required', label: 'Signature Required', category: 'Fulfillment & E-commerce' },

  // Other
  { value: 'miscellaneous', label: 'Miscellaneous', category: 'Other' },
  { value: 'other', label: 'Other', category: 'Other' },
] as const

export type RateComponentType = typeof RATE_COMPONENTS[number]['value']

// Group rate components by category
export const RATE_COMPONENTS_BY_CATEGORY = RATE_COMPONENTS.reduce((acc, component) => {
  if (!acc[component.category]) {
    acc[component.category] = []
  }
  acc[component.category].push(component)
  return acc
}, {} as Record<string, typeof RATE_COMPONENTS[number][]>)

// Get label for a component type
export const getRateComponentLabel = (value: string): string => {
  const component = RATE_COMPONENTS.find(c => c.value === value)
  return component?.label || value
}
